superlists/lists/urls.py
from django.conf.urls import url
from lists import views

 
urlpatterns = [
    url(r'^$', views.homePage, name='homePage'),
    #url(r'^the-only-list-in-the-world/$', views.viewList, name='viewList'),
    url(r'^(?P<listID>[0-9]+)/$', views.viewList, name='viewList'),
    url(r'^new/', views.newList, name='newList'),
]

superlists/superlists/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('lists.urls')),
    url(r'^lists/', include('lists.urls', namespace='lists')),
]

superlists/lists/models.py
from django.db import models

# Create your models here.
class List(models.Model):
    pass

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

superlists/lists/forms.py
from django.utils.html import escape
from django import forms
from lists.models import Item


EMPTY_ITEM_ERROR = escape('清單項目不能空白')



class ItemForm(forms.ModelForm):
    
    class Meta:
        model = Item
        fields = ('text', )
        widgets = {
            'text':forms.fields.TextInput(attrs={
                'placeholder':'輸入一個待辦項目',
                'class':'form-control input-lg',
            }),
        }
        error_messages = {
            'text':{'required':EMPTY_ITEM_ERROR},
        }

superlists/lists/views.py
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.utils.html import escape
from lists.models import Item, List
from lists.forms import ItemForm

def homePage(request):
    return render(request, 'lists/home.html', {'form':ItemForm()})

def viewList(request, listID):
    list_ = List.objects.get(id=listID)
    error = None
    if request.method=='POST':
        try:
            item = Item.objects.create(text=request.POST.get('itemText'), list=list_)
            item.full_clean()
            item.save()
            return redirect(reverse('lists:viewList', args=(list_.id, )))
        except ValidationError:
            error = escape('清單項目不能空白')
    return render(request, 'lists/list.html', {'list':list_, 'error':error})


def newList(request):
    list_ = List.objects.create()
    item = Item(text=request.POST.get('itemText'), list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = escape('清單項目不能空白')
        return render(request, 'lists/home.html', {'error':error})
    return redirect(reverse('lists:viewList', args=(list_.id, )))




    

superlists/lists/templates/lists/base.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>待辦事項清單</title>
<meta charset=utf-8>
<link rel=stylesheet href=http://getbootstrap.com/dist/css/bootstrap.min.css>
<link rel=stylesheet href={% static 'lists/css/base.css' %}>
</head>
<body>

<div class=container>

  <div class=row>
    <div class="col-md-6 col-md-offset-3 jumbotron">
      <div class=text-center>
        <h1>{% block headerText %}{% endblock %}</h1>
        <form method=POST action={% block formAction %}{% endblock %}>
	      {% csrf_token %}
	      <input class="form-control input-lg" id=newItem name=itemText placeholder=輸入一個待辦事項>
          {% if error %}
            <div class="form-group has-error">
              <span class=help-block>{{error}}</span>
            </div>
          {% endif %}
	    </form>
      </div>
    </div>
  </div>
    
  <div class=row>
    <div class="col-md-6 col-md-offset-3">
      {% block table %}
      {% endblock %}
    </div>
  </div>

</div>

</body>
</html>

superlists/lists/templates/lists/home.html
{% extends "lists/base.html" %}
{% block headerText %}開啟一個新的待辦事項清單{% endblock %}
{% block formAction %}{% url 'lists:newList' %}{% endblock %}>

superlists/lists/templates/lists/list.html
{% extends "lists/base.html" %}
{% block headerText %}您的待辦事項清單{% endblock %}
{% block formAction %}{% url 'lists:viewList' list.id %}{% endblock %}>
{% block table %}
<table class=table id=listTable>
  {% for item in list.item_set.all %}
    <tr><td>{{item.text}}</td></tr>
  {% endfor %}
</table>
{% endblock %}